name: Generate MATLAB Reports
on: [push]
jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - uses: matlab-actions/setup-matlab@v2
            - uses: matlab-actions/run-command@v2
              with:
                command: addpath("./Matlab/HH"), addpath("./Matlab/utils"), HH_demo, save_all_open_figs("export", "fig_")
            - uses: actions/upload-artifact@v4
              with:
                name: matlab-figures
                path: Matlab/HH/export/**
                if-no-files-found: error
